---
# Using Docker Compose for Dev Containers: https://containers.dev/guide/dockerfile#docker-compose-dockerfile
# Service top-level element reference: https://docs.docker.com/compose/compose-file/05-services/
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    environment:
      # Enable Docker BuildKit https://docs.docker.com/build/buildkit/
      DOCKER_BUILDKIT: '1'
    volumes:
      - ../..:/workspaces:cached    # mounts the workspace folder from the local source tree into the Dev Container.
    command: sleep infinity
