---
# Using Docker Compose for Dev Containers: https://containers.dev/guide/dockerfile#docker-compose-dockerfile
# Service top-level element reference: https://docs.docker.com/compose/compose-file/05-services/
services:
  devcontainer:
    depends_on:
      mysql:
        condition: service_healthy
    image: mcr.microsoft.com/devcontainers/base:bullseye
    environment:
      # Enable Docker BuildKit https://docs.docker.com/build/buildkit/
      DOCKER_BUILDKIT: '1'
      # Externalized Spring Configuration: https://docs.spring.io/spring-boot/docs/1.5.6.RELEASE/reference/html/boot-features-external-config.html
      # Connect to MySQL: mysql --host=mysql --user=$SPRING_DATASOURCE_USERNAME --password=$SPRING_DATASOURCE_PASSWORD demoapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: local
    network_mode: service:mysql    # puts the Dev Container on the same network as the database, so that it can access it on localhost
    volumes:
      - ../..:/workspaces:cached    # mounts the workspace folder from the local source tree into the Dev Container.
    command: sleep infinity
  mysql:    # Service name is also used as hostname when connecting from other containers
    image: mysql:8.0    # https://hub.docker.com/_/mysql
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: demoapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      # Login to mysql demoapp db
      test: mysql --host=localhost --user=root --password=$$MYSQL_ROOT_PASSWORD demoapp    # command for testing health
      # Specifying durations: https://docs.docker.com/compose/compose-file/11-extension/#specifying-durations
      interval: 5s    # specifies the time duration or interval in which the healthcheck process will execute
      timeout: 1s     # defines the time duration to wait for a healthcheck
      retries: 10     # is used to define the number of tries to implement the health check after failure
    restart: unless-stopped
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql

# Volumes top-level element reference: https://docs.docker.com/compose/compose-file/07-volumes/
volumes:
  mysql-data: {}
